---
title: "Seen Stats"
---


```{r}
library(tidyverse)
library(reshape2)

# Load data
votes <- readr::read_csv("../data-clean/votes.csv")
```

```{r}
# Filter out rows with "Seen" as "NA - Critics' Pick"
votes_filtered <- votes %>%
  filter(Seen != "NA - Critics' Pick")

# Remove unnecessary columns
votes <- votes_filtered %>%
  select(-Category, -MovieNominee, -Nominee, -Critic, -color, -Movie) %>%
  distinct(Alias, .keep_all = TRUE)  # Keep unique alias with all columns

# Split the "Seen" column into separate movies
votes$Seen <- strsplit(votes$Seen, ", ")

# Create a list of unique movies
all_movies <- unique(unlist(votes$Seen))

# Create a matrix or data frame to store the results
result_df <- matrix(0, nrow = nrow(votes), ncol = length(all_movies), dimnames = list(NULL, all_movies))

# Populate the matrix with 1s and 0s
for (i in 1:nrow(votes)) {
  result_df[i, votes$Seen[[i]]] <- 1
}

# Convert the matrix to a data frame and add the Alias column
results <- data.frame(Alias = votes$Alias, result_df)

# Replace dots with spaces in column names
colnames(results) <- gsub("\\.", " ", colnames(results))

# Calculate total movies seen by each alias
results$total_movies_seen <- rowSums(results[, -1])

```



```{r}
# Movies Seen Most
movies_seen_most <- result_df %>%
  select(-total_movies_seen) %>%
  summarise(across(-Alias, sum)) %>%
  pivot_longer(cols = everything(), names_to = "movie", values_to = "count") %>%
  arrange(desc(count)) %>%
  head()
```

```{r}
# Table showing people who have seen the most movies
people_seen_most <- result_df %>%
  select(Alias, total_movies_seen) %>%
  arrange(desc(total_movies_seen)) %>%
  head()
```


```{r}
# Unique movies seen by only 1 person
unique_movies <- result_df %>%
  pivot_longer(cols = -Alias, names_to = "movie", values_to = "seen") %>%
  filter(seen == 1) %>%
  group_by(movie) %>%
  filter(n_distinct(Alias) == 1) %>%
  summarise(Alias = first(Alias))

unique_movies
```





